name: "steam_fullmarket"
version: "1.0.0"
config-version: 2

profile: "steam_fullmarket"

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
macro-paths: [ "macros" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  steam_fullmarket:
    staging:
      +materialized: view
    marts:
      +materialized: table
